spring:
  application:
    name: employee-db
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver      

server:
  port: 8083
  
app:
  path: C:\\Users\\fabio.dossantosestre\\eclipse-workspace\\filesystem
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/